#!/bin/bash

python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/64/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/64/1 --sensitive_attribute 130 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/64/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose
python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/64/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/64/1 --sensitive_attribute 595 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/64/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose


python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/1 --sensitive_attribute 130 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose
python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/1 --sensitive_attribute 595 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose

python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/5/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/5 --sensitive_attribute 130 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose
python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/5/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/5 --sensitive_attribute 595 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose

python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/10/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/10 --sensitive_attribute 130 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose
python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/32/10/federated.json --device cuda --seed 42 --results_dir ./results/purchase/32/10 --sensitive_attribute 595 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/32/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose


python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/1000/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/1000/1 --sensitive_attribute 130 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/1000/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose
python evaluate_aia.py --task_name purchase --models_metadata_path ./metadata/purchase/1000/1/federated.json --device cuda --seed 42 --results_dir ./results/purchase/1000/1 --sensitive_attribute 595 --sensitive_attribute_type binary --split train --reference_models_metadata_path ./metadata/purchase/1000/1/local_trajectories.json --data_dir ./data/purchase --models_config_metadata_path ./metadata/purchase/model_config.json --verbose